spring:
  application:
    name: xQuiz

  profiles:
    active: dev, local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/xQuiz-db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  sql:
    init:
      mode: always
      platform: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api

# application config :
application:
  front-url: ${FRONT_URL:http://localhost:3000}
